
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# INFO-уровень логирования для продакшена
logging.level.root=INFO

# Путь для файловых логов (используется в logback-spring.xml)
logging.file.path=logs

