
# Локальная БД для разработки
spring.datasource.url=jdbc:postgresql://localhost:5432/products_uqc2
spring.datasource.username=postgres
spring.datasource.password=1234

# DEBUG-уровень логирования для удобной диагностики
logging.level.root=DEBUG

