# Привязка конфигурации под разработку (dev)
# Включайте этот профиль: -Dspring.profiles.active=dev или SPRING_PROFILES_ACTIVE=dev

# Локальная БД для разработки
spring.datasource.url=jdbc:postgresql://localhost:5432/products_uqc2
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate/Flyway настройки оставляем из application.properties (при необходимости можно переопределить здесь)

# DEBUG-уровень логирования для удобной диагностики
logging.level.root=DEBUG

